### ISSUE TITLE
YML 파일 수정 관련 

### ISSUE THREAD

**Issue by maketext** [rchemist/demo-micro-front-mono#10]
안녕하세요.

1. RDB와 레디스만 사용하려고 합니다. 몽고DB와 엘라스틱 서치를 사용하지 않으려면 이렇게 설정하면 되는 것인지 확인 부탁드립니다. 추가적으로 false 해야 할 항목이 있으면 알려주세요.
###### resoucres/bootstrap.yml 파일 수정
```
platform:
  config:
    provider:
      search: querydsl    #검색엔진을 사용할 것인지(hibernate), 그냥 DB에서 검색할 지(querydsl) 선택한다. querydsl | hibernate 둘 중 하나의 값을 사용할 수 있다.
      elastic: false
      mongo: false
```
2. DB 커넥션을 위해 마리아 DB 5.5 사용시 아래와 같이 설정하면 되는지 확인 부탁드립니다.
```
spring:
  datasource:
    rcm-rdb:
      promotion:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://{대상서버주소}/{스키마}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        password: {패스워드}
        url: jdbc:mariadb://{대상서버주소}/{스키마}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
        username: {유저네임}
        hibernate:
          cache:
            use_query_cache: true
            use_second_level_cache: true
            redisson:
              entity-offer:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-offer:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              entity-dynamicPrice:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
              query-dynamicPrice:
                eviction:
                  max_entries: 100000
                expiration:
                  time_to_live: 86400000
          dialect: org.hibernate.dialect.MariaDB53Dialect
          hbm2ddl:
            auto: update
          show_sql: true
```
###### 의존성 추가
```
<dependency>
  <groupId>org.mariadb.jdbc</groupId>
  <artifactId>mariadb-java-client</artifactId>
  <version>3.0.3</version>
</dependency>
```
3. HTTPS 설정시 일반적인 설정 방법을 사용하면 되는지 따로 설정 방법이 있는지 문의드립니다.
###### 기존 yml 파일
```
server:
  port: 8000
https:
  port: 8010
```
###### 일반 설정
```
server:
  port: {지정}
  ssl:
        enabled: true
        key-store: "cert.jks" 또는 "cert.pfx" 지정 
        key-store-type: 인증서 파일 포맷별 "JKS" 또는 "PKCS12" 지정 
        key-store-password: xxxxxxxx  # 암호
```
